name: python-deployment

run-name: ${{ github.actor }} - ${{ github.ref_name }} - ${{ github.sha }}

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version to use'
        required: true
        default: '3.8'
      os-type:
        description: 'Operating System to use'
        required: true
        default: 'ubuntu-latest'

env:
  PythonVersion: 3.8
  DockerImageName: todoapp

jobs:
  python-ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9']
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage flake8
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test

      - name: Generate Report
        run: |
          coverage run --source='.' manage.py test
          coverage report

      - name: Linting
        run: |
          flake8 . --show-source --statistics --exit-zero

      - name: Check Complexity
        run: |
          flake8 . --exit-zero --max-complexity=6

      - name: Upload python artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-artifacts-${{ github.run_id }}-${{ matrix.os }}-${{ matrix.python-version }}
          path: .
        # Updated: Added `github.run_id`, `matrix.os`, and `matrix.python-version` to ensure a unique artifact name.

      - name: Upload helm artifacts
        if: github.ref_name == 'main'
        uses: actions/upload-artifact@v4
        with:
          name: helm-artifacts-${{ github.run_id }}-${{ matrix.os }}-${{ matrix.python-version }}
          path: ${{ github.workspace }}/helm-charts
        # Updated: Added `github.run_id`, `matrix.os`, and `matrix.python-version` to ensure a unique artifact name.

      - name: Upload kind cluster artifact
        if: github.ref_name == 'main'
        uses: actions/upload-artifact@v4
        with:
          name: kind-cluster-${{ github.run_id }}-${{ matrix.os }}-${{ matrix.python-version }}
          path: ${{ github.workspace }}/cluster.yml
        # Updated: Added `github.run_id`, `matrix.os`, and `matrix.python-version` to ensure a unique artifact name.

  docker-ci:
    name: Build and Push Image
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    needs: python-ci
    steps:

    - uses: actions/download-artifact@v4
      name: Download python artifacts
      with:
        name: python-artifacts-${{ github.run_id }}-ubuntu-latest-3.8
        path: .
      # Updated: Modified to download the uniquely named python artifacts for `ubuntu-latest` and `3.8`. 
      # If this needs to be more dynamic, consider parameterizing the artifact name based on the specific combination of OS and Python version.

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        context: ./src
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DockerImageName }}:${{ github.sha }}

  helm-ci:
    runs-on: ubuntu-latest
    needs: python-ci
    if: github.ref_name == 'main'
    name: Helm CI
    steps:

    - uses: actions/download-artifact@v4
      with:
        name: helm-artifacts-${{ github.run_id }}-ubuntu-latest-3.8
        path: .
      # Updated: Modified to download the uniquely named Helm artifacts for `ubuntu-latest` and `3.8`.

    - name: Set Up Helm
      uses: azure/setup-helm@v4.2.0

    - name: Lint helm
      run: helm lint ./todoapp/

    - name: Template Helm
      run: helm template todoapp ./todoapp/ -f ./todoapp/values.yaml

    - name: Package Helm
      run: helm package ./todoapp

    - name: Upload Helm Artifact
      uses: actions/upload-artifact@v4
      with:
        name: helm-package-${{ github.run_id }}
        path: ./*.tgz
      # Updated: Added `github.run_id` to ensure a unique artifact name for Helm package artifacts.

  deploy-helm-dev:
    name: Deploy helm to Development
    uses: ./.github/workflows/reusable-deployment.yml
    needs: [helm-ci, docker-ci]
    secrets: inherit
    with:
      environment: development
      version: ${{ github.sha }}
      helm-values-path: ${{ github.event.inputs.helm-values-path }}
      helm-release-name: ${{ github.event.inputs.helm-release-name }}

  deploy-helm-stg:
    name: Deploy helm to Staging
    uses: ./.github/workflows/reusable-deployment.yml
    needs: [deploy-helm-dev]
    secrets: inherit
    with:
      environment: staging
      version: ${{ github.sha }}
      helm-values-path: ./todoapp/values/stg.yaml
      helm-release-name: todoapp-staging
