name: helm-upgrade
run-name: ${{ github.actor }} - ${{ github.ref_name }} - ${{ github.sha }}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: 'Environment to deploy to'
        type: string
      version:
        required: true
        type: string
      helm-values-path:
        type: string
        default: './todoapp/values.yaml'
      helm-release-name:
        default: todoapp
        type: string

jobs:
  deploy-helm:
    name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Download Helm Package
      uses: actions/download-artifact@v4
      with:
        name: helm-package
        path: .

    # Debugging step to confirm artifact download
    - name: List Files in Current Directory
      run: ls -alh

    # Ensure the cluster.yml file is present
    - name: Check for cluster.yml
      run: |
        if [ ! -f ./cluster.yml ]; then
          echo "cluster.yml file not found!"
          exit 1
        fi

    - name: Set Up Helm
      uses: azure/setup-helm@v4.2.0

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v4

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1
      with:
        config: ./cluster.yml

    - name: Dry Run Helm
      run: |
        helm install --dry-run ${{ inputs.helm-release-name }} ./todoapp-*.tgz  \
        -f ${{ inputs.helm-values-path }} \
        --set mysql.secrets.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
        --set mysql.secrets.MYSQL_USER="${{ secrets.MYSQL_USER }}" \
        --set mysql.secrets.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
        --set todoapp.secrets.SECRET_KEY="${{ secrets.SECRET_KEY }}" \
        --set todoapp.secrets.DB_NAME="${{ secrets.APP_DB_NAME }}" \
        --set todoapp.secrets.DB_USER="${{ secrets.MYSQL_USER }}" \
        --set todoapp.secrets.DB_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
        --set todoapp.secrets.DB_HOST="${{ secrets.APP_DB_HOST }}" \
        --set todoapp.image.tag=${{ github.sha }}

    - name: Deploy helm to Development
      run: |
        helm upgrade --install --wait --timeout 180s --debug ${{ inputs.helm-release-name }} ./todoapp-*.tgz \
        -f ${{ inputs.helm-values-path }} \
        --set mysql.secrets.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
        --set mysql.secrets.MYSQL_USER="${{ secrets.MYSQL_USER }}" \
        --set mysql.secrets.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
        --set todoapp.secrets.SECRET_KEY="${{ secrets.SECRET_KEY }}" \
        --set todoapp.secrets.DB_NAME="${{ secrets.APP_DB_NAME }}" \
        --set todoapp.secrets.DB_USER="${{ secrets.MYSQL_USER }}" \
        --set todoapp.secrets.DB_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
        --set todoapp.secrets.DB_HOST="${{ secrets.APP_DB_HOST }}" \
        --set todoapp.image.tag=${{ github.sha }}
